language: go
go:
  - '1.11'
  - master
script:
   - go test -v ./...
   - go build -o ./binary/hello_world_app
deploy:
  provider: s3
  access_key_id: AKIAI3EBWH7UDETTUYQA
  secret_access_key:
    secure: fpZqXDXV8QGYHpVh9AJjq4y/bY6IDEM1wuBdHcatibS8TAtqzd1uMvpKrsYZ+zdL/teXdE568xaUGishuVNu/B0K8x1LYCFp8yAEvD+r0CguU3KZHe2GZFdL9sxzo80hbg8Q4TwmjrY4B356dXgykbglwr9tAgFpqts2QnlXPXSXvdGEA3zgXStmq7fQ61JU+edffWewBjkK0K/LJRwuzwfd0CDB0+osN66WIW11m9LX1uQxL3faCE69CvZmSzvsJz9PUVU5hvz6pW0XmPDgGknjZpOxHnFszsAcXa7Q6nvWguJPyEGLz074h2C+ZqnUlMdFJBuLntXRwvPjdKJqV2TnQMhEFkyKftK6ewOYuUYKvsxttiRfzLidLdEZBdvbjmGIGbnVnGFbDxi3UOyVHoy0pYlNHWwJ3pddTnlDZUz9Da7cGi27HNqH72W6iEygBwn8gonDgaCNsqTkt9NTkSsdnIAUzEh6xTWHhF+Bhh/z/FJIOSakiltSCTr2Lp5YZQP9VzbSYgrwhFgTboSG9ydvWGL3TkpARDxT4hh05tEhIS6WtCK0estE7p5axCEjakRbO5DYkBH7/T5oPmWhUeCtlQKY9hRN6NMMHv57Zm5ISt9crxVDLePGxbkZL2MdOl/YxqUirD5Bcr8xH7kMyQGAN/rRqKE2z4WusxqXycs=
  bucket: 20190125asssignment-thaniri
  acl: ''
  on:
    repo: thaniri/20190125Asssignment
  skip_cleanup: true
  localdir: binary
